%1
ostatni(Element,[A]):-Element=A.
ostatni(Element,[_|END]):-ostatni(Element,END).
%2
przedostatni(Element,[A|[_]]):-Element=A.
przedostatni(Element,[_|END]):-przedostatni(Element,END).
%3
bezostatniego(L1,L2):-L1=[_],L2=[].
bezostatniego([A|END],[A|L2]):-A=_,bezostatniego(END,L2).
%4
nakoniec(Element,L1,L2):-L1=[],L2=[Element].
nakoniec(Element,[A|END],[A|L2]):-A=_,nakoniec(Element,END,L2).
%5
podwajaj(L1,L2):-L1=[],L2=[].
podwajaj([A|END],[A|[A|L2]]):-A=_,podwajaj(END,L2).
%6
codrugi(L1,L2):-L1=[_],L2=[].
codrugi(L1,L2):-L1=[],L2=[].
codrugi([_|[B|END]],[B|L2]):-B=_,codrugi(END,L2).
%7
splataj(LA,LB,LS):-LA=[],LB=[],LS=[].
splataj([A|ENDA],[B|ENDB],[A|[B|LS]]):-A=_,B=_,splataj(ENDA,ENDB,LS).
%8
lewoprawo(X,[A|L],[A|END],LP):-A=_,lewoprawo(X,L,END,LP).
lewoprawo(X,L,[],LP):-L=[X|LP].
%9
wymiana(X,Y,[],[]):-X=_,Y=_.
wymiana(X,Y,[X|END1],[Y|END2]):-X=_,Y=_,wymiana(X,Y,END1,END2).
wymiana(X,Y,[A|END1],[A|END2]):-X=_,Y=_,wymiana(X,Y,END1,END2).
%10
polacz([],[]).
polacz([X|Y],Z):-polacz(Y,A),append(X,A,Z).
