package com.sample.rules
 
import com.sample.DroolsTest.*;

rule "Init"
	when
	then
        insert(new Pomiar(true, 160));
        insert(new Pomiar(true, 170));
end
 
rule "PaliSie"
    when
        exists Pomiar( dym == true, temperatura > 150 )
    then
        insert(new Pozar());
end

rule "PozarSieZaczal"
    when
        Pozar( )
    then
        System.out.println( "Pali sie!" );
end

rule "ReakcjaNaPozar"
    when
        Pozar( )
    then
        insert(new Telefon(112));
end

rule "PodanoTelefon"
	when
		t: Telefon ( )
	then
		System.out.println("Prosze zadzwonic na " + t.numer + '!');
		//update(t) //punkt7
end

rule "Straz Przyjechala"
	when
		Straz()
		p: Pozar() // Dopasowanie obiektu Pozar
	then
		retract(p);
		System.out.println("Straz przyjechala!");
end

rule "Odjazd Strazy"
	when
		Straz()
		not Pozar()
	then
		System.out.println("Odjezdzamy!");
end
