package com.sample.rules
 
import com.sample.DroolsTest.*;

rule "Init"
	when
	then
		Osoba maria          = new Osoba("Maria");
		Osoba ewa            = new Osoba("Ewa");
		Osoba agata          = new Osoba("Agata");
		Osoba anna           = new Osoba("Anna");
		Osoba agnieszka      = new Osoba("Agnieszka");
		Osoba beata          = new Osoba("Beata");
		Osoba iwona          = new Osoba("Iwona");
		Osoba joanna         = new Osoba("Joanna");
		Osoba piotr          = new Osoba("Piotr");
		Osoba adam           = new Osoba("Adam");
		Osoba marek          = new Osoba("Marek");
		Osoba robert         = new Osoba("Robert");
		Osoba jan            = new Osoba("Jan");
		Osoba krzysztof      = new Osoba("Krzysztof");
		Osoba radek          = new Osoba("Radek");
		Osoba darek          = new Osoba("Darek");
		Osoba tomek          = new Osoba("Tomek");
		Osoba jacek          = new Osoba("Jacek");

		insert(new Relacja(maria,marek,"rodzic"));
		insert(new Relacja(maria,agata,"rodzic"));
		insert(new Relacja(maria,jan,"rodzic"));
		insert(new Relacja(piotr,marek,"rodzic"));
		insert(new Relacja(piotr,agata,"rodzic"));
		insert(new Relacja(piotr,jan,"rodzic"));
		insert(new Relacja(ewa,anna,"rodzic"));
		insert(new Relacja(ewa,joanna,"rodzic"));
		insert(new Relacja(ewa,krzysztof,"rodzic"));
		insert(new Relacja(adam,anna,"rodzic"));
		insert(new Relacja(adam,joanna,"rodzic"));
		insert(new Relacja(adam,krzysztof,"rodzic"));
		insert(new Relacja(agata,radek,"rodzic"));
		insert(new Relacja(agata,beata,"rodzic"));
		insert(new Relacja(robert,radek,"rodzic"));
		insert(new Relacja(robert,beata,"rodzic"));
		insert(new Relacja(anna,darek,"rodzic"));
		insert(new Relacja(anna,tomek,"rodzic"));
		insert(new Relacja(jan,darek,"rodzic"));
		insert(new Relacja(jan,tomek,"rodzic"));
		insert(new Relacja(agnieszka,jacek,"rodzic"));
		insert(new Relacja(agnieszka,iwona,"rodzic"));
		insert(new Relacja(krzysztof,jacek,"rodzic"));
		insert(new Relacja(krzysztof,iwona,"rodzic"));
		
end


rule "Ustal plec"
when
    $relacja: Relacja() // Pobranie każdej relacji
    $osoba1: Osoba(this != null) from $relacja.osoby[0]
    $osoba2: Osoba(this != null) from $relacja.osoby[1]
    Osoba(plec == Plec.NIEZNANA) from $relacja.osoby
then
    if ($osoba1 != null && $osoba1.plec == Plec.NIEZNANA) {
        insert($osoba1);
        modify($osoba1) {
            plec = $osoba1.imie.matches(".*a$") ? Plec.KOBIETA : Plec.MEZCZYZNA
        }
        
        int liczbaRelacjiOsoba1 = $osoba1.relacje.size();
        System.out.println("Po ustaleniu płci, osoba 1: " + $osoba1.imie + ", Płeć: " + $osoba1.plec + ", Liczba relacji: " + liczbaRelacjiOsoba1);
        
        
        for (Relacja r : $osoba1.relacje) {
            update(r);
        }
    }

    if ($osoba2 != null && $osoba2.plec == Plec.NIEZNANA) {
        insert($osoba2);
        modify($osoba2) {
            plec = $osoba2.imie.matches(".*a$") ? Plec.KOBIETA : Plec.MEZCZYZNA
        }
        
        int liczbaRelacjiOsoba2 = $osoba2.relacje.size();
        System.out.println("Po ustaleniu płci, osoba 2: " + $osoba2.imie + ", Płeć: " + $osoba2.plec + ", Liczba relacji: " + liczbaRelacjiOsoba2);
        
        
        for (Relacja r : $osoba2.relacje) {
            update(r);
        }
    }
end


rule "Ojciec"
when
    $relacja: Relacja(relacja == "rodzic")
    $osoba1: Osoba(this != null, plec == Plec.MEZCZYZNA) from $relacja.osoby[0]
    $osoba2: Osoba(this != null) from $relacja.osoby[1]
then
    Relacja ojciec = new Relacja($osoba1, $osoba2, "ojciec");
    insert(ojciec);
    System.out.println($osoba1.imie + " jest ojcem " + $osoba2.imie);
end

rule "Matka"
when
    $relacja: Relacja(relacja == "rodzic")
    $osoba1: Osoba(this != null, plec == Plec.KOBIETA) from $relacja.osoby[0]
    $osoba2: Osoba(this != null) from $relacja.osoby[1]
then
    Relacja matka = new Relacja($osoba1, $osoba2, "matka");
    insert(matka);
    System.out.println($osoba1.imie + " jest matką " + $osoba2.imie);
end


rule "Babcia"
when
    $matka: Relacja(relacja == "matka")
    $rodzic: Relacja(relacja == "rodzic", osoby[0] == $matka.osoby[1])
then
    Relacja babcia = new Relacja($matka.osoby[0], $rodzic.osoby[1], "babcia");
    insert(babcia);
    System.out.println($matka.osoby[0].imie + " jest babcia " + $rodzic.osoby[1].imie);
end

rule "Dziadek"
when
    $ojciec: Relacja(relacja == "ojciec")
    $rodzic: Relacja(relacja == "rodzic", osoby[0] == $ojciec.osoby[1])
then
    Relacja dziadek = new Relacja($ojciec.osoby[0], $rodzic.osoby[1], "dziadek");
    insert(dziadek);
    System.out.println($ojciec.osoby[0].imie + " jest dziadkiem " + $rodzic.osoby[1].imie);
end


rule "siostra"
when
    $rodzic: Relacja(relacja == "matka", osoby[1].plec == Plec.KOBIETA)
    $rodzic2: Relacja(relacja == "matka", osoby[0] == $rodzic.osoby[0], osoby[1] != $rodzic.osoby[1])
then
    Relacja siostra = new Relacja($rodzic.osoby[1], $rodzic2.osoby[1], "siostra");
    insert(siostra);
    System.out.println($rodzic.osoby[1].imie + " jest siostra " + $rodzic2.osoby[1].imie);
end

rule "brat"
when
    $rodzic: Relacja(relacja == "matka", osoby[1].plec == Plec.MEZCZYZNA)
    $rodzic2: Relacja(relacja == "matka", osoby[0] == $rodzic.osoby[0], osoby[1] != $rodzic.osoby[1])
then
    Relacja brat = new Relacja($rodzic.osoby[1], $rodzic2.osoby[1], "brat");
    insert(brat);
    System.out.println($rodzic.osoby[1].imie + " jest bratem " + $rodzic2.osoby[1].imie);
end



rule "Stryj"
when
    $ojciec: Relacja(relacja == "ojciec")
    $brat: Relacja(relacja == "brat", osoby[1] == $ojciec.osoby[0])
then
    Relacja stryj = new Relacja($brat.osoby[0], $ojciec.osoby[1], "stryj");
    insert(stryj);
    System.out.println($brat.osoby[0].imie + " jest stryjem " + $ojciec.osoby[1].imie);
end

rule "Wujek"
when
    $matka: Relacja(relacja == "matka")
    $brat: Relacja(relacja == "brat", osoby[1] == $matka.osoby[0])
then
    Relacja wujek = new Relacja($brat.osoby[0], $matka.osoby[1], "wujek");
    insert(wujek);
    System.out.println($brat.osoby[0].imie + " jest wujkiem " + $matka.osoby[1].imie);
end



query "Stryjowie dla osoby" (String imie)
    $stryj: Relacja(osoby[1].imie == imie, relacja == "stryj")
end

query "Wujkowie dla osoby" (String imie)
    $wujek: Relacja(osoby[1].imie == imie, relacja == "wujek")
end



rule "Kuzyn"
when
    $rel1: Relacja(relacja == "rodzic")
    $rel2: Relacja(osoby[1] == $rel1.osoby[0], osoby[0].plec == Plec.KOBIETA, relacja == "rodzic")
    $rel3: Relacja(osoby[1] != $rel2.osoby[1], osoby[0] == $rel2.osoby[0], relacja == "rodzic")
    $rel4: Relacja(osoby[0] == $rel3.osoby[1], relacja == "rodzic")
then
    Relacja kuzyn = new Relacja($rel1.osoby[1], $rel4.osoby[1], "kuzyn");
    insert(kuzyn);
    System.out.println($rel1.osoby[1].imie + " jest kuzynem " + $rel4.osoby[1].imie);
end
